baseURL: "https://masa162.github.io/IKUTA_GREEN/" # 新しいリポジトリ名に後で変更します
languageCode: "ja"
title: "IKUTA GREEN PARK PORTAL"
theme: "PaperMod"

# config.yml

menu:
  main:
    - identifier: plants
      name: "Plants"
      url: "/plants/"
      weight: 10
    - identifier: animals
      name: "Animals"
      url: "/animals/"
      weight: 20
    - identifier: history
      name: "History"
      url: "/history/"
      weight: 30
    - identifier: map
      name: "Map"
      url: "/map/"
      weight: 40

params:
  profileMode:
    enabled: true
    title: "IKUTA GREEN PARK PORTAL"
    subtitle: " "
    imageUrl: "/images/forest-bg.jpg"
    imageWidth: 1200
    imageHeight: 600
    buttons:
      - name: Plants
        url: "/plants/"
      - name: Animals
        url: "/animals/"
      - name: History
        url: "/history/"
      - name: Map
        url: "/map/"

  assets:
    favicon: "/images/leaf-icon.png"
    custom_css:
      - css/custom.scss

outputs:
    home:
        - HTML
        - RSS
        - JSON